#for debian
set(CPACK_PACKAGE_NAME ${PROJECT_NAME}
    CACHE STRING "The resulting package name"
)

set(CPACK_PACKAGE_VENDOR "Gustavo Bastian")
set(CPACK_VERBATIM_VARIABLES YES)
set(CPACK_PACKAGE_INSTALL_DIRECTORY ${CPACK_PACKAGE_NAME})
Set(CPACK_OUTPUT_FILE_PREFIX "${CMAKE_SOURCE_DIR}/_packages")
# https://unix.stackexchange.com/a/11552/254512
set(CPACK_PACKAGING_INSTALL_PREFIX "/opt/csv2sqlite3")#/${CMAKE_PROJECT_VERSION}")

set (CPACK_PACKAGE_CONTACT "bastian.gustavo@gmail.com")
set(CPACK_DEBIAN_PACKAGE_MAINTAINER "Gustavo Bastian")


set(CPACK_RESOURCE_FILE_LICENSE "${CMAKE_CURRENT_SOURCE_DIR}/LICENSE")
set(CPACK_RESOURCE_FILE_README "${CMAKE_CURRENT_SOURCE_DIR}/README.md")

set(CPACK_DEBIAN_FILE_NAME DEB-DEFAULT)

set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "csv to sqlite 3"
    CACHE STRING "Package description for the package metadata"
)
set (CPACK_DEBIAN_PACKAGE_ARCHITECTURE i386)
set(CPACK_DEBIAN_PACKAGE_DESCRIPTION "Simple console app that imports csv file to sqlite 3")
set(CPACK_DEBIAN_PACKAGE_HOMEPAGE "https://www.gabiot.com.ar")
set(CPACK_PACKAGE_CONTACT “bastian.gustavo@gmail.com”)

set(CPACK_PROJECT_NAME ${PROJECT_NAME})
set(CPACK_PROJECT_VERSION ${PROJECT_VERSION})
set(CPACK_PROJECT_LICENSE MIT)
set(CMAKE_MODULE_PATH "${CMAKE_CURRENT_SOURCE_DIR}/cmake")
install(TARGETS csv2sqlite3 RUNTIME DESTINATION bin)


include(CPack)

